# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Words < Formula
  desc "极客就要用终端来背单词"
  homepage "https://github.com/LinkinStars/words"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/LinkinStars/words/releases/download/v0.1.6/words_darwin_arm64.tar.gz"
      sha256 "9283f6b3d289fb3810f9ea7c35fc8cec7bb3c49f4b7760a46f6835e011acd830"

      def install
        bin.install "words"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/LinkinStars/words/releases/download/v0.1.6/words_darwin_amd64.tar.gz"
      sha256 "f693a55b2139fe692db606dba2d49aff5964efb86b07b3be80463bfbd89d35dd"

      def install
        bin.install "words"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/LinkinStars/words/releases/download/v0.1.6/words_linux_amd64.tar.gz"
      sha256 "19f8a4422390386f89e8841758a673b22b7c9f7f4d0db0dcd3c038abffb6b273"

      def install
        bin.install "words"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LinkinStars/words/releases/download/v0.1.6/words_linux_arm64.tar.gz"
      sha256 "a29c76900de999a7dcc6f6a26cc57e0bc940647c423d484117ad832648141c48"

      def install
        bin.install "words"
      end
    end
  end
end
